name: Learning CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.7'
    - name: Install dependencies
      working-directory: ../django_authen_api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      working-directory: ../django_authen_api
      run: python manage.py migrate
    - name: Run tests
      working-directory: ../django_authen_api
      run: python manage.py test
