name: Learning CICD

on: [push]

defaults:
  run:
    working-directory: ./django_authen_api
    

jobs:
  build:
    name: test and build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test
  heroku_git_deploy_job:
      needs: [ build ]
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
          with:
              docker_heroku_process_type: web
              heroku_api_key: c548e174-86bc-41b8-9949-88d0bb3c7cc0
              heroku_app_name: django-cicd
              heroku_email: "trungtruong.working@gmail.com"
              justlogin: true
        - name: login to heroku registry
          run: heroku container:login
        - name: build image and retag
          run: |
            docker build -t django-cicd . && docker tag django-cicd registry.heroku.com/django-cicd/web
        - name: push to heroku
          run: docker push registry.heroku.com/django-cicd/web
        - name: release image
          run: heroku container:release web -a django-cicd
